[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Gustavo de Paula Gorges", email = "gustavodep.gorges@gmail.com"},
]
dependencies = [
    "django>=4.1.7",
]
requires-python = ">=3.10"
license = {text = "MIT"}
